#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Sean Lane

# Short bio or description (displayed in the header)
description: BYU Computer Science graduate student

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/sean.png

# Timezone for the site
timezone: America/Denver

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: hi@sean.lane.sh
  facebook:
  flickr: seanlane
  github: seanlane
  gitlab: seanlane
  googleplus: # anything in your profile username that comes after plus.google.com/
  hackernews: seanlane
  instagram:
  keybase: seanlane
  linkedin: SeanTLane
  mastodon: mastodon.technology/@seanlane
  pinterest:
  reddit: _seanlane
  rss: anything # just type anything here for a working RSS icon, make sure you set the "url" above!
  skype:
  soundcloud:
  stackoverflow: users/3685023/sean-lane # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  tumblr:
  twitter: _seanlane
  youtube: # channel/<your_long_string> or user/<user-name>


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-31520487-4

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://sean.lane.sh

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# If using GitHub to host comments (as described in 
# http://sean.lane.sh/blog/2016/Hosting_comments_within_issues_on_Github_Pages)
# set this value to the GitHub user and project (for example seanlane/seanlane.github.io)
comments_uri: seanlane/seanlane.github.io

# Options for paginate
paginate: 10
paginate_path: "/blog/page/:num"

# Other flags for jekyll-seo-tag

author: Sean Lane
google_site_verification: 63TafJC6wM1WPYOuSj6KA9dDFaFW9x5y6Ita9qytSYk
logo: /images/sean.png
social:
  links:
    - https://www.linkedin.com/in/SeanTLane
    - https://twitter.com/_seanlane
    - https://github.com/seanlane
    - https://gitlab.com/u/seanlane
    - https://www.flickr.com/photos/seanlane
twitter:
  username: _seanlane

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
#markdown: kramdown
#kramdown:
  input: GFM
 # extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
#highlighter: rouge
permalink: /blog/:year/:title
future: true
# The release of Jekyll Now that you're using
version: v3.6.2

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate # Create pages for blog posts
  - jekyll-seo-tag  # Add SEO tags to Jekyll templates

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - _drafts
    - project_files
    - wishlist.md
